CREATE TABLE [dbo].[Пациенты]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Фамилия] NCHAR(10) NULL, 
    [Имя] NCHAR(10) NULL, 
    [Отчество] NCHAR(10) NULL, 
    [Время заполнения] TIMESTAMP NULL, 
    [Пол] BIT NULL, 
    [Субъект РФ] NCHAR(64) NULL, 
    [Район] NCHAR(64) NULL, 
    [Город] NCHAR(64) NULL, 
    [Улица] NCHAR(64) NULL, 
    [Дом] NCHAR(64) NULL, 
    [Корпус] NCHAR(5) NULL, 
    [Квартира] NCHAR(10) NULL, 
    [Телефон] NCHAR(10) NULL, 
    [Местность] BIT NULL, 
    [Полис серия] NCHAR(10) NULL, 
    [Полис номер] NCHAR(10) NULL, 
    [СНИЛС] NCHAR(12) NULL, 
    [Страховая] INT NULL, 
    [Код льготы] NCHAR(10) NULL, 
    [Группа трудоспособности] NCHAR(10) NULL, 
    [Документ серия] NCHAR(10) NULL, 
    [Документ номер] NCHAR(10) NULL, 
    [Семейное положение] SMALLINT NULL, 
    [Образование] SMALLINT NULL, 
    [Работа] SMALLINT NULL, 
    [Группа крови] SMALLINT NULL, 
    [Rh] SMALLINT NULL, 
    [Аллергия] NCHAR(128) NULL, 
    CONSTRAINT [FK_Пациенты_ToСтраховые] FOREIGN KEY ([Страховая]) REFERENCES [Страховые организации]([Id])
)
